# Generated by Django 4.0.6 on 2022-08-02 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(0, 'BORROWED'), (1, 'AVAILABLE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
